server:
  port: 8080
spring:
  datasource:
    username: root
    password: 967557fxh
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
  security:
    user:
      name: fxh
      password: 123456
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
jasypt:
  encryptor:
    password: demo

