server:
  port: 8080
spring:
  datasource:
    username: root
    password: 967557fxh
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
  security:
    user:
      name: fxh
      password: 123456
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
jasypt:
  encryptor:
    password: demo
logging:
 # config: log4j2-spring.xml #默认的日志配置文件名是log4j2-spring.xml ,如果是默认的配置文件名则可以不需要配置文件名，否则需要配置文件名
  level:
    cn.jay.repository: trace
